### ISSUE TITLE
A Noobs Guide to signing and the script!

### ISSUE THREAD

**Issue by TheMainlander** [jellicoe/EVERNODE_WITHDRAW#1]
OK, I think I understand the process of having to have an XAH Account in Xaman which I have FULL Control of.

Then I add the Nide addresses which I also own but allow my XAH Parent account to sign off on that node for the Daily Reward.

But, do I add this script to each Node and  what would be the best practice here before applying a script?

When I say best practice I also mean, robust security and Firewalls too ...

And I would also expect that this could be tested first as well for newcomers.

Thank you. :)

**Comment by jellicoe** [comment]
you do not need to run this from any node 

just run it from a terminal on any machine  that supports nodejs 

once you configure the .env file to your accounts - its pretty straight forward 

the only one odd exercise is for each node to set the regular key to point to your master / signing wallet 

with running this on ya nodes

$ evernode regkey set rWalletAddressThatYouOwnThatCanSignTransactions

you don't really need to add each node address to xaman - its just a view thing
